"""Media storage abstraction.

Files are written through a `MediaStorage` interface so the backing store can
move to S3/Cloudinary later without touching the product system. Only
`LocalDiskStorage` ships today; swap the `get_storage()` return value.

Security rules enforced here:
  * the client-supplied filename is NEVER used on disk — a UUID name is
    generated, which removes path traversal and overwrite risk entirely
  * extension AND magic-byte sniffing must agree on the type
  * a hard size cap is applied while streaming, so a huge upload cannot be
    buffered into memory first
"""
import os
import uuid
from abc import ABC, abstractmethod
from typing import BinaryIO, Tuple

MAX_IMAGE_BYTES = 8 * 1024 * 1024     # 8 MB
MAX_VIDEO_BYTES = 64 * 1024 * 1024    # 64 MB
CHUNK = 1024 * 1024

IMAGE_TYPES = {
    "image/jpeg": ".jpg",
    "image/png": ".png",
    "image/webp": ".webp",
}
VIDEO_TYPES = {
    "video/mp4": ".mp4",
    "video/webm": ".webm",
}

# Leading bytes used to confirm the declared content type is truthful.
MAGIC = {
    "image/jpeg": [b"\xff\xd8\xff"],
    "image/png": [b"\x89PNG\r\n\x1a\n"],
    "image/webp": [b"RIFF"],          # RIFF....WEBP
    "video/mp4": [b"\x00\x00\x00"],   # ....ftyp
    "video/webm": [b"\x1a\x45\xdf\xa3"],
}


class UploadRejected(ValueError):
    """Raised when an upload fails validation."""


def _sniff_ok(content_type: str, head: bytes) -> bool:
    if content_type not in MAGIC:
        return False
    if content_type == "image/webp":
        return head[:4] == b"RIFF" and head[8:12] == b"WEBP"
    if content_type == "video/mp4":
        return b"ftyp" in head[:16]
    return any(head.startswith(sig) for sig in MAGIC[content_type])


def validate_and_classify(content_type: str, head: bytes) -> Tuple[str, str, int]:
    """Return (media_type, extension, max_bytes) or raise UploadRejected."""
    ct = (content_type or "").split(";")[0].strip().lower()
    if ct in IMAGE_TYPES:
        kind, ext, cap = "image", IMAGE_TYPES[ct], MAX_IMAGE_BYTES
    elif ct in VIDEO_TYPES:
        kind, ext, cap = "video", VIDEO_TYPES[ct], MAX_VIDEO_BYTES
    else:
        raise UploadRejected(
            "Unsupported file type. Allowed: JPG, PNG, WEBP images and MP4, WEBM video."
        )
    if not _sniff_ok(ct, head):
        raise UploadRejected(
            "File contents do not match the declared file type and were rejected."
        )
    return kind, ext, cap


class MediaStorage(ABC):
    @abstractmethod
    def save(self, stream: BinaryIO, extension: str, max_bytes: int) -> Tuple[str, int]:
        """Persist a stream. Returns (storage_key, bytes_written)."""

    @abstractmethod
    def url_for(self, storage_key: str) -> str:
        """Public URL for a stored object."""

    @abstractmethod
    def delete(self, storage_key: str) -> None:
        """Remove a stored object; must not raise if already gone."""


class LocalDiskStorage(MediaStorage):
    """Development/simple-deployment storage under a media root."""

    def __init__(self, root: str, public_prefix: str = "/media"):
        self.root = os.path.abspath(root)
        self.public_prefix = public_prefix.rstrip("/")
        os.makedirs(self.root, exist_ok=True)

    def _path(self, storage_key: str) -> str:
        # Keys are generated by us (uuid + ext). Re-validate anyway so a
        # tampered key can never escape the media root.
        safe = os.path.basename(storage_key)
        full = os.path.abspath(os.path.join(self.root, safe))
        if not full.startswith(self.root + os.sep) and full != self.root:
            raise UploadRejected("Invalid storage key.")
        return full

    def save(self, stream: BinaryIO, extension: str, max_bytes: int):
        storage_key = f"{uuid.uuid4().hex}{extension}"
        path = self._path(storage_key)
        written = 0
        try:
            with open(path, "wb") as out:
                while True:
                    chunk = stream.read(CHUNK)
                    if not chunk:
                        break
                    written += len(chunk)
                    if written > max_bytes:
                        out.close()
                        os.remove(path)
                        raise UploadRejected(
                            f"File is too large (limit {max_bytes // (1024 * 1024)} MB)."
                        )
                    out.write(chunk)
        except UploadRejected:
            raise
        except Exception:
            if os.path.exists(path):
                os.remove(path)
            raise
        if written == 0:
            os.remove(path)
            raise UploadRejected("Uploaded file is empty.")
        return storage_key, written

    def url_for(self, storage_key: str) -> str:
        return f"{self.public_prefix}/{storage_key}"

    def delete(self, storage_key: str) -> None:
        try:
            os.remove(self._path(storage_key))
        except (FileNotFoundError, UploadRejected):
            pass


_storage: MediaStorage = None


def get_storage() -> MediaStorage:
    """Swap this for S3Storage/CloudinaryStorage in production."""
    global _storage
    if _storage is None:
        from app.config import settings
        _storage = LocalDiskStorage(settings.MEDIA_ROOT, settings.MEDIA_URL_PREFIX)
    return _storage
