"""Media storage abstraction.

Files are written through a `MediaStorage` interface, so where a file lives
is decided here and nowhere else. There are two stores:

  * site media — Back Office content images, category images. Always
    `LocalDiskStorage`: plain files under MEDIA_ROOT, served at /media.
    `get_storage()`.
  * product media — product photographs and videos. `S3Storage` when
    PRODUCT_MEDIA_STORAGE=s3 (production), otherwise the same local disk.
    `get_product_storage()`.

A stored file is found again by its key: S3 keys start with S3_PREFIX and
local keys never do, so `storage_for_key()` sends a delete to the store that
actually holds the file, including rows written before the switch to S3.

Security rules enforced here:
  * the client-supplied filename is NEVER used on disk — a UUID name is
    generated, which removes path traversal and overwrite risk entirely
  * extension AND magic-byte sniffing must agree on the type
  * a hard size cap is applied while streaming, so a huge upload cannot be
    buffered into memory first
"""
import logging
import os
import tempfile
import uuid
from abc import ABC, abstractmethod
from typing import BinaryIO, Tuple

log = logging.getLogger(__name__)

MAX_IMAGE_BYTES = 8 * 1024 * 1024     # 8 MB
MAX_VIDEO_BYTES = 64 * 1024 * 1024    # 64 MB
CHUNK = 1024 * 1024

IMAGE_TYPES = {
    "image/jpeg": ".jpg",
    "image/png": ".png",
    "image/webp": ".webp",
}
VIDEO_TYPES = {
    "video/mp4": ".mp4",
    "video/webm": ".webm",
}

# Leading bytes used to confirm the declared content type is truthful.
MAGIC = {
    "image/jpeg": [b"\xff\xd8\xff"],
    "image/png": [b"\x89PNG\r\n\x1a\n"],
    "image/webp": [b"RIFF"],          # RIFF....WEBP
    "video/mp4": [b"\x00\x00\x00"],   # ....ftyp
    "video/webm": [b"\x1a\x45\xdf\xa3"],
}


class UploadRejected(ValueError):
    """Raised when an upload fails validation."""


def _sniff_ok(content_type: str, head: bytes) -> bool:
    if content_type not in MAGIC:
        return False
    if content_type == "image/webp":
        return head[:4] == b"RIFF" and head[8:12] == b"WEBP"
    if content_type == "video/mp4":
        return b"ftyp" in head[:16]
    return any(head.startswith(sig) for sig in MAGIC[content_type])


def validate_and_classify(content_type: str, head: bytes) -> Tuple[str, str, int]:
    """Return (media_type, extension, max_bytes) or raise UploadRejected."""
    ct = (content_type or "").split(";")[0].strip().lower()
    if ct in IMAGE_TYPES:
        kind, ext, cap = "image", IMAGE_TYPES[ct], MAX_IMAGE_BYTES
    elif ct in VIDEO_TYPES:
        kind, ext, cap = "video", VIDEO_TYPES[ct], MAX_VIDEO_BYTES
    else:
        raise UploadRejected(
            "Unsupported file type. Allowed: JPG, PNG, WEBP images and MP4, WEBM video."
        )
    if not _sniff_ok(ct, head):
        raise UploadRejected(
            "File contents do not match the declared file type and were rejected."
        )
    return kind, ext, cap


class MediaStorage(ABC):
    @abstractmethod
    def save(self, stream: BinaryIO, extension: str, max_bytes: int) -> Tuple[str, int]:
        """Persist a stream. Returns (storage_key, bytes_written)."""

    @abstractmethod
    def url_for(self, storage_key: str) -> str:
        """Public URL for a stored object."""

    @abstractmethod
    def delete(self, storage_key: str) -> None:
        """Remove a stored object; must not raise if already gone."""


class LocalDiskStorage(MediaStorage):
    """Development/simple-deployment storage under a media root."""

    def __init__(self, root: str, public_prefix: str = "/media"):
        self.root = os.path.abspath(root)
        self.public_prefix = public_prefix.rstrip("/")
        os.makedirs(self.root, exist_ok=True)

    def _path(self, storage_key: str) -> str:
        # Keys are generated by us (uuid + ext). Re-validate anyway so a
        # tampered key can never escape the media root.
        safe = os.path.basename(storage_key)
        full = os.path.abspath(os.path.join(self.root, safe))
        if not full.startswith(self.root + os.sep) and full != self.root:
            raise UploadRejected("Invalid storage key.")
        return full

    def save(self, stream: BinaryIO, extension: str, max_bytes: int):
        storage_key = f"{uuid.uuid4().hex}{extension}"
        path = self._path(storage_key)
        written = 0
        try:
            with open(path, "wb") as out:
                while True:
                    chunk = stream.read(CHUNK)
                    if not chunk:
                        break
                    written += len(chunk)
                    if written > max_bytes:
                        out.close()
                        os.remove(path)
                        raise UploadRejected(
                            f"File is too large (limit {max_bytes // (1024 * 1024)} MB)."
                        )
                    out.write(chunk)
        except UploadRejected:
            raise
        except Exception:
            if os.path.exists(path):
                os.remove(path)
            raise
        if written == 0:
            os.remove(path)
            raise UploadRejected("Uploaded file is empty.")
        return storage_key, written

    def url_for(self, storage_key: str) -> str:
        return f"{self.public_prefix}/{storage_key}"

    def delete(self, storage_key: str) -> None:
        try:
            os.remove(self._path(storage_key))
        except (FileNotFoundError, UploadRejected):
            pass


# Every S3 key starts with this; no local key can (local keys are a bare
# "<uuid>.<ext>"), which is how a key tells which store holds it.
S3_PREFIX = "products/"
CONTENT_TYPES = {ext: ct for ct, ext in {**IMAGE_TYPES, **VIDEO_TYPES}.items()}
# A stored object is never rewritten (every upload gets a new name), so a
# browser may keep it for a year.
IMMUTABLE = "public, max-age=31536000, immutable"


class S3Storage(MediaStorage):
    """Product media in an S3 bucket, served straight from it.

    The bucket's policy makes S3_PREFIX publicly readable; nothing else in it
    is. The instance role needs s3:PutObject and s3:DeleteObject on that
    prefix and nothing more.
    """

    def __init__(self, bucket: str, region: str, public_url: str = "", client=None):
        if not bucket:
            raise ValueError("S3Storage needs a bucket name.")
        self.bucket = bucket
        self.region = region
        self.public_url = (public_url or
                           f"https://{bucket}.s3.{region}.amazonaws.com").rstrip("/")
        self._client = client

    @property
    def client(self):
        if self._client is None:
            import boto3      # only needed when S3 is actually in use
            self._client = boto3.client("s3", region_name=self.region)
        return self._client

    def save(self, stream: BinaryIO, extension: str, max_bytes: int):
        storage_key = f"{S3_PREFIX}{uuid.uuid4().hex}{extension}"
        written = 0
        # Streamed through a spooled temp file so the size cap applies before
        # anything is sent, and a large video does not sit in memory.
        with tempfile.SpooledTemporaryFile(max_size=CHUNK * 8) as buf:
            while True:
                chunk = stream.read(CHUNK)
                if not chunk:
                    break
                written += len(chunk)
                if written > max_bytes:
                    raise UploadRejected(
                        f"File is too large (limit {max_bytes // (1024 * 1024)} MB)."
                    )
                buf.write(chunk)
            if written == 0:
                raise UploadRejected("Uploaded file is empty.")
            buf.seek(0)
            self.put(buf, storage_key)
        return storage_key, written

    def put(self, fileobj: BinaryIO, storage_key: str) -> None:
        """Upload an already-validated file under an exact key."""
        ext = os.path.splitext(storage_key)[1].lower()
        self.client.upload_fileobj(
            fileobj, self.bucket, storage_key,
            ExtraArgs={"ContentType": CONTENT_TYPES.get(ext, "application/octet-stream"),
                       "CacheControl": IMMUTABLE},
        )

    def url_for(self, storage_key: str) -> str:
        return f"{self.public_url}/{storage_key}"

    def delete(self, storage_key: str) -> None:
        # S3 does not fail on a missing key. Any other failure is logged, not
        # raised: removing a product must not be blocked by a stray object.
        try:
            self.client.delete_object(Bucket=self.bucket, Key=storage_key)
        except Exception:        # noqa: BLE001
            log.warning("Could not delete s3://%s/%s", self.bucket, storage_key, exc_info=True)


_storage: MediaStorage = None
_product_storage: MediaStorage = None


def get_storage() -> MediaStorage:
    """Site media: plain files under MEDIA_ROOT."""
    global _storage
    if _storage is None:
        from app.config import settings
        _storage = LocalDiskStorage(settings.MEDIA_ROOT, settings.MEDIA_URL_PREFIX)
    return _storage


def _s3_from_settings() -> S3Storage:
    from app.config import settings
    return S3Storage(settings.PRODUCT_MEDIA_BUCKET, settings.PRODUCT_MEDIA_REGION,
                     settings.PRODUCT_MEDIA_PUBLIC_URL)


def get_product_storage() -> MediaStorage:
    """Where new product photographs and videos are written."""
    global _product_storage
    if _product_storage is None:
        from app.config import settings
        _product_storage = (_s3_from_settings() if settings.PRODUCT_MEDIA_STORAGE == "s3"
                            else get_storage())
    return _product_storage


def storage_for_key(storage_key: str) -> MediaStorage:
    """The store that holds an existing file, whatever new files use."""
    if storage_key and storage_key.startswith(S3_PREFIX):
        product = get_product_storage()
        if isinstance(product, S3Storage):
            return product
        from app.config import settings
        if settings.PRODUCT_MEDIA_BUCKET:
            return _s3_from_settings()
    return get_storage()
